In [2]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
import numpy as np
from sklearn.preprocessing import StandardScaler
%matplotlib inline

In [4]:
food = ['SepalLength','x1','SepalWidth','x2','PetalLength','x3','petalWidth','x4','species']
df = pd.read_csv('iris.csv', names=food)


In [6]:
df.head()

SepalLength        x1  SepalWidth        x2  PetalLength        x3  \
0          5.1  0.222222         3.5  0.625000          1.4  0.067797   
1          4.9  0.166667         3.0  0.416667          1.4  0.067797   
2          4.7  0.111111         3.2  0.500000          1.3  0.050847   
3          4.6  0.083333         3.1  0.458333          1.5  0.084746   
4          5.0  0.194444         3.6  0.666667          1.4  0.067797   

   petalWidth        x4 species  
0         0.2  0.041667  setosa  
1         0.2  0.041667  setosa  
2         0.2  0.041667  setosa  
3         0.2  0.041667  setosa  
4         0.2  0.041667  setosa

In [8]:
df.shape

(100, 9)

In [7]:
df.species.unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [77]:
df=df.iloc[:,[0,2,4,6,8]]

In [78]:
df.head(2)

SepalLength  SepalWidth  PetalLength  petalWidth species
0          5.1         3.5          1.4         0.2  setosa
1          4.9         3.0          1.4         0.2  setosa

In [79]:
labels = df['species']
X = df.drop(['species'], axis = 1)

In [80]:
X_standard = StandardScaler()

In [81]:
X_standardized = StandardScaler().fit_transform(X)

In [82]:
# let us ask it to create a PCA with four features
#By passing all four features or components we are asking it to tell us howmany of them are useful
pca = PCA(n_components = 4)

X_transform = pca.fit_transform(X_standardized)

pca.explained_variance_

array([ 2.91362753,  0.91947418,  0.15295583,  0.01394246])

In [83]:
X_transform

array([[ -2.35601988e+00,   4.70699287e-01,  -9.99164200e-02,
         -1.11813399e-02],
       [ -2.16313468e+00,  -6.68989404e-01,  -2.39514373e-01,
         -9.42463956e-02],
       [ -2.44274712e+00,  -3.46089665e-01,   3.96928465e-02,
         -1.04011976e-02],
       [ -2.37495091e+00,  -5.99216622e-01,   7.32584340e-02,
          8.41796798e-02],
       [ -2.47943185e+00,   6.32895578e-01,   4.27628087e-02,
          5.34002416e-02],
       [ -2.17494683e+00,   1.46658741e+00,   9.21677438e-02,
          8.70559830e-03],
       [ -2.52009579e+00,   3.37125319e-02,   3.37587235e-01,
          6.25414503e-02],
       [ -2.32101217e+00,   2.16079486e-01,  -7.25020705e-02,
          3.80815726e-02],
       [ -2.40330098e+00,  -1.11293475e+00,   1.09633419e-01,
          4.67516100e-02],
       [ -2.26925217e+00,  -4.65300688e-01,  -2.61010939e-01,
          4.86651016e-02],
       [ -2.26707343e+00,   1.03137559e+00,  -2.18262575e-01,
         -8.01653464e-03],
       [ -2.40941642e

In [84]:
#The first two components explain all the variance because adding them amoiunts to > 90& of the total variance
pca.explained_variance_ratio_

array([ 0.72840688,  0.22986854,  0.03823896,  0.00348561])

In [85]:
#X2 = X.iloc[:,0:2]
X_standard = StandardScaler()
X_standardized = StandardScaler().fit_transform(X)
pca1 = PCA(n_components = 2)
X2_transform = pca.fit_transform(X_standardized)

In [87]:
pca.explained_variance_

array([ 2.91362753,  0.91947418,  0.15295583,  0.01394246])

In [88]:
pca.explained_variance_ratio_

array([ 0.72840688,  0.22986854,  0.03823896,  0.00348561])

In [89]:
X2_transform

array([[ -2.35601988e+00,   4.70699287e-01,  -9.99164200e-02,
         -1.11813399e-02],
       [ -2.16313468e+00,  -6.68989404e-01,  -2.39514373e-01,
         -9.42463956e-02],
       [ -2.44274712e+00,  -3.46089665e-01,   3.96928465e-02,
         -1.04011976e-02],
       [ -2.37495091e+00,  -5.99216622e-01,   7.32584340e-02,
          8.41796798e-02],
       [ -2.47943185e+00,   6.32895578e-01,   4.27628087e-02,
          5.34002416e-02],
       [ -2.17494683e+00,   1.46658741e+00,   9.21677438e-02,
          8.70559830e-03],
       [ -2.52009579e+00,   3.37125319e-02,   3.37587235e-01,
          6.25414503e-02],
       [ -2.32101217e+00,   2.16079486e-01,  -7.25020705e-02,
          3.80815726e-02],
       [ -2.40330098e+00,  -1.11293475e+00,   1.09633419e-01,
          4.67516100e-02],
       [ -2.26925217e+00,  -4.65300688e-01,  -2.61010939e-01,
          4.86651016e-02],
       [ -2.26707343e+00,   1.03137559e+00,  -2.18262575e-01,
         -8.01653464e-03],
       [ -2.40941642e